
language: R
sudo: required
cache: packages

addons:
  apt:
    packages:
      - libgsl0-dev # for topicmodels
      - libudunits2-dev # for ggraph

warnings_are_errors: true

after_success:
- Rscript -e 'covr::codecov()'

before_install:
 - echo "options(repos = c(CRAN='http://cran.rstudio.com'))" >> ~/.Rprofile

apt_packages:
 - curl
 - libcurl4-openssl-dev

r_binary_packages:
 - topicmodels
 - rmpfr