
language: R
sudo: false
cache: packages

addons:
  apt:
    packages:
      - libgsl0-dev # for topicmodels
      - libudunits2-dev # for ggraph
      - libggforce-dev #ggforce

after_success:
- Rscript -e 'covr::codecov()'